# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages 

name: Node.js Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: "@dxos"
      - run: | 
          git config --global user.email "npm@dxos.network"
          git config --global user.name "DxOS"
          yarn
          yarn test
          yarn version --new-version `yarn --json info $(jq -r .name package.json) dist-tags.$TAG | jq -r '.data' | awk -F"." '{for (i=1; i<NF; i++) printf $i"."; print $NF+1}'`
          yarn build
          yarn publish --tag beta --access public
          git push --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
